spring:
  profiles:
    active:
      - dev
---
spring: 
  profiles: dev   #开发环境
  application: 
    name: springcloud-config-wyx-dev007
config:
  info: "114514"
---
spring: 
  profiles: test   #测试环境
  application: 
    name: springcloud-config-wyx-test007
config:
  info: "1919810"
# UTF-8保存

# 测试GitHub的操作
